name: flutter_radio
description: A Flutter audio plugin for Android to play remote audio files using ExoPlayer
version: 0.0.3
author: Thyago Luciano <thyagoluciano@gmail.com>
homepage: https://github.com/thyagoluciano/flutter_radio

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    androidPackage: br.com.thyagoluciano.flutterradio
    pluginClass: FlutterRadioPlugin

environment:
  sdk: ">=1.19.0 <=2.0.0"
